targetSystem: "linux"

datadog:
  # datadog.apiKey -- Your Datadog API key
  # ref: https://app.datadoghq.com/account/settings#agent/kubernetes
  apiKey: 
  
  # datadog.site -- The site of the Datadog intake to send Agent data to
  ## Set to 'datadoghq.eu' to send data to the EU site.
  site: datadoghq.com

  env:
    - name: DD_ENV
      value: "gui"
  
  ## Enable apm agent and provide custom configs
  apm:
    # datadog.apm.portEnabled -- Enable APM over TCP communication (port 8126 by default)
    ## ref: https://docs.datadoghq.com/agent/kubernetes/apm/
    portEnabled: true

  ## @param logs - object - required
  ## Enable logs agent and provide custom configs
  #
  logs:
    ## @param enabled - boolean - optional - default: false
    ## Enables this to activate Datadog Agent log collection.
    #
    enabled: true

    ## @param containerCollectAll - boolean - optional - default: false
    ## Enable this to allow log collection for all containers.
    #
    containerCollectAll: true

  processAgent:
    enabled: true
    processCollection: true

  kubeStateMetricsCore:
    enabled: true

  clusterName: guilherme

  # CASO SEJA MINI KUBE OU NOS LOGS ESTEJA ACUSANDO PROBLEMA DE VERIFICAÇÃO TLS MANTENHA AS LINHAS ABAIXO
  # SE NAO SE ENQUADRA NOS CASOS DESCRITOS ACIMA, REMOVER TODAS AS LINHAS ABAIXO 
  # kubelet configuration
  kubelet:
    # datadog.kubelet.tlsVerify -- Toggle kubelet TLS verification
    # @default -- true
    tlsVerify: false
